### ISSUE TITLE
Better way to modify GeoSeries values?

### ISSUE THREAD

**Issue by jamesmaino** [EcoJulia/RasterDataSources.jl#15]
I had to adjust the values for the precipitation layer (-33000 for NA) and realised that the GeoSeries consisted of `DataStack`s where the data are immutable. Here is my solution but I feel like there must be a better way. Any suggestions @rafaqz ?

```julia
using Interpolations, RasterDataSources, Dates, GeoData, ArchGDAL
using Plots

# download monthly mean data from WorldClim at the 10 m resoltution
months = 1:12
layers = (:tavg, :prec)
getraster(WorldClim{Climate}, layers, months, "10m")
ser_immut = series(WorldClim{Climate}, layers; res="10m")

dates = (DateTime(2001, 1, 1):Month(1):DateTime(2001, 12, 1))
ser = [GeoStack(ser_immut[i]) for i = 1:12] 
ser = GeoSeries( ser, (Ti(dates),))

for i in 1:12    
    ser[i][:prec] .= map(x -> x < 0 ? 0 : x, ser1[i][:prec])
end

plot(ser_immut[1][:prec])

plot(ser[1][:prec])


```

**Comment by jamesmaino** [comment]
It's even worse now! I had to convert the same layer from Int to Float (was throwing an error in GrowthMaps). 

```julia
using TimeInterpolatedGeoData
using Interpolations, RasterDataSources, Dates, GeoData, ArchGDAL

# download monthly mean data from WorldClim at the 10 m resoltution
months = 1:12
layers = (:tavg, :prec)
getraster(WorldClim{Climate}, layers, months, "10m")
ser_immut = series(WorldClim{Climate}, layers; res="10m")

dates = (DateTime(2001, 1, 1):Month(1):DateTime(2001, 12, 1))
ser = [GeoStack(ser_immut[i][:tavg], float(ser_immut[i][:prec]); 
    keys = (:tavg, :prec)) for i = 1:12] 
ser = GeoSeries(ser, (Ti(dates),))
for i in 1:12    
    ser[i][:prec] .= map(x -> x < 0 ? 0.0 : x, ser[i][:prec])
end

plot(ser_immut[1][:prec])

plot(ser[1][:prec])
```

**Comment by rafaqz** [comment]
It's not so much immutable as on-disk. Do you want to change the values is the stored arrays or just use them in-memory?

Also "It's even worse now" is kind of unhelpful. Can you post an error message and REPL code that triggered it.


But to change the internal array of a GeoArray, GeoStack, Geoseries and any variant of that, use `modify`:

```julia
modify(series) do A
    Float32.(A) # do something to the internal Array A, here convert values to Float32
end
```

To change the dates index, use:
```julia
dates = DateTime(2001, 1, 1):Month(1):DateTime(2001, 12, 1)
set(series, Ti=dates)
```

**Comment by jamesmaino** [comment]
Should have mentioned it worked. There is no error message - I just thought my code was clunky. 

Where is `modify`?

**Comment by rafaqz** [comment]
Oh right I thought you meant it was a bug that breaks GrowthMaps.jl. 

`modify` is  a DD function that GeoData extends for stacks and series.

**Comment by rafaqz** [comment]
Hah reading this its funny the answer is the `modify` method, given the title. 

Did this resolve things? Can we close this?

**Comment by jamesmaino** [comment]
Yes, thanks! Nice naming ;)
