### ISSUE TITLE
Elevation from WorldClim?

### ISSUE THREAD

**Issue by Mikumikunisiteageru** [EcoJulia/RasterDataSources.jl#55]
I would like to use the elevation raster data from WorldClim (https://www.worldclim.org/data/worldclim21.html) in practice to keep in line with their bioclimatic layers. However, I notice that it is not yet accessible with RasterDataSources.jl. Although it was derived from SRTM, it requires much space and time to prepare the low-resolution elevation rasters from SRTM again. Thus, I request the direct access to these coarse-grid elevation raster data.

**Comment by rafaqz** [comment]
Make a PR! Its pretty easy to copy the form of the other WorldClim sources.

I am very unlikely to do it otherwise, I use SRTM
